/**
 * Emit cross-language parity vectors for the daily rack order.
 *
 * The Swift engine is a hand port of src/engine/rack.ts, and the two seed
 * derivations differ in ways that are easy to get subtly wrong (Math.imul is a
 * wrapping multiply; the attempt salt is not). If they diverge, a player sees
 * one rack on the web and a different one in the app for the same day. This
 * writes the TypeScript answers into the Swift test suite as fixtures.
 *
 * Run from the web repo root:
 *   node scripts/rack-parity.mjs > ../peach-of-a-word-swift/Tests/PeachEngineTests/RackParityVectors.swift
 */
import { readFileSync } from 'node:fs';
import { dailyRackOrder } from '../src/engine/rack.ts';

const words = JSON.parse(
  readFileSync('public/data/daily-calendar.json', 'utf8'),
).words;

const rows = words.map((word) => {
  const letters = [...word].sort().join('');
  return `    ("${word}", [${dailyRackOrder(letters, word).join(', ')}]),`;
});

process.stdout.write(`// GENERATED by scripts/rack-parity.mjs in the web repo. Do not edit by hand.
//
// The daily rack order as the TypeScript engine deals it, for every word in the
// committed calendar. RackTests replays these through the Swift engine, so a
// divergence in the seed derivation fails a test instead of shipping two
// different puzzles for one day.

let rackParityVectors: [(String, [Int])] = [
${rows.join('\n')}
]
`);
